# Generated by the Nibble compiler.

.data

.align 4
ga: 
.long 10


.text
.globl main
main:
    push %rbp
    movq %rsp, %rbp

    subq $16, %rsp
    movl $10, -4(%rbp)
    jmp while.cond.0
    while.top.0:
    movl -4(%rbp), %r10d
    subl $1, %r10d
    movl %r10d, -4(%rbp)
    while.cond.0:
    movl -4(%rbp), %r10d
    cmp $0, %r10d
    jne while.top.0
    movl -4(%rbp), %r10d
    addl $2, %r10d
    movl %r10d, %eax
    jmp end.main
    end.main:
    movq %rbp, %rsp
    pop %rbp
    ret
