; Generated by the Nibble compiler.

SECTION .data


SECTION .text
global main
main:
    push rbp
    mov rbp, rsp

    sub rsp, 48
    mov dword [rbp + -4], 1
    mov dword [rbp + -8], 1
    mov dword [rbp + -12], 2
    mov dword [rbp + -16], 3
    mov dword [rbp + -20], 4
    mov dword [rbp + -24], 5
    mov dword [rbp + -28], 6
    lea r10, dword [rbp + -28]
    mov qword [rbp + -40], r10
    mov r10, qword [rbp + -40]
    mov r11, qword [rbp + -40]
    mov r11d, dword [r11]
    movsxd rdi, r11d
    neg rdi
    movsxd r11, dword [rbp + -4]
    sub rdi, r11
    movsxd r11, dword [rbp + -8]
    add rdi, r11
    mov r10d, dword [r10 + 4*rdi + 28]
    mov eax, r10d
    jmp end.main
    end.main:
    mov rsp, rbp
    pop rbp
    ret
