#include "nibble.h"
#include "compiler.h"
#include "parser.h"
#include "bytecode.h"
#include "code_gen.h"
#include "path_utils.h"

static NibbleCtx* nibble;

const char* os_names[NUM_OS] = {
    [OS_LINUX] = "linux",
    [OS_WIN32] = "win32",
    [OS_OSX] = "osx",
};

const char* arch_names[NUM_ARCH] = {
    [ARCH_X86] = "x86",
    [ARCH_X64] = "x64",
};

const char* keyword_names[KW_COUNT];
const char* annotation_names[ANNOTATION_COUNT];
const char* intrinsic_names[INTRINSIC_COUNT];

Identifier* main_proc_ident;

char* slurp_file(Allocator* allocator, const char* filename)
{
    FILE* fd = fopen(filename, "r");
    if (!fd) {
        NIBBLE_FATAL_EXIT("Failed to open file %s", filename);
        return NULL;
    }

    if (fseek(fd, 0, SEEK_END) < 0) {
        NIBBLE_FATAL_EXIT("Failed to read file %s", filename);
        return NULL;
    }

    long int size = ftell(fd);
    if (size < 0) {
        NIBBLE_FATAL_EXIT("Failed to read file %s", filename);
        return NULL;
    }

    char* buf = mem_allocate(allocator, size + 1, DEFAULT_ALIGN, false);
    if (!buf) {
        NIBBLE_FATAL_EXIT("Out of memory: %s:%d", __FILE__, __LINE__);
        return NULL;
    }

    if (fseek(fd, 0, SEEK_SET) < 0) {
        NIBBLE_FATAL_EXIT("Failed to read file %s", filename);
        return NULL;
    }

    size_t n = fread(buf, 1, (size_t)size, fd);
    if (ferror(fd)) {
        NIBBLE_FATAL_EXIT("Failed to read file %s", filename);
        return NULL;
    }

    fclose(fd);

    buf[n] = '\0';

    return buf;
}

void report_error(const char* filename, ProgRange range, const char* format, ...)
{
    // TODO: range should just have line and column numbers instead of byte offsets.
    (void)range;

    // TODO: Use an allocator + string writer.
    char buf[MAX_ERROR_LEN];
    va_list vargs;

    size_t size = snprintf(buf, MAX_ERROR_LEN, "%s:0:0 ", filename);

    if (size < MAX_ERROR_LEN) {
        size_t rem = MAX_ERROR_LEN - size;
        char* ptr = buf + size;

        va_start(vargs, format);
        size += vsnprintf(ptr, rem, format, vargs) + 1;
        va_end(vargs);
    }

    if (size >= MAX_ERROR_LEN) {
        buf[MAX_ERROR_LEN - 1] = '\0';
        size = MAX_ERROR_LEN;
    }

    add_byte_stream_chunk(&nibble->errors, buf, size);
}

static void print_errors(ByteStream* errors)
{
    if (errors->count > 0) {
        ftprint_out("\nErrors: %lu\n", errors->count);

        ByteStreamChunk* chunk = errors->first;

        while (chunk) {
            ftprint_out("%s\n", chunk->buf);

            chunk = chunk->next;
        }
    }
}

static bool init_annotations()
{
    static const StringView names[ANNOTATION_COUNT] = {
        [ANNOTATION_EXPORTED] = string_view_lit("exported"),
        [ANNOTATION_FOREIGN] = string_view_lit("foreign"),
        [ANNOTATION_PACKED] = string_view_lit("packed"),
    };

    for (int i = 0; i < ANNOTATION_COUNT; i += 1) {
        const StringView* str_view = names + i;
        Identifier* ident = intern_ident(str_view->str, str_view->len);

        if (!ident) {
            return false;
        }

        annotation_names[i] = ident->str;
    }

    return true;
}


/*
// Code for the builtin module that is automatically imported everywhere:
// Generated by: xxd -i builtin.nib
// NOTE: A terminating null character has to be added to the output of xxd

proc #writeout(buf: ^char, size: usize) => ssize;

proc #readin(buf: ^char, size: usize) => ssize;
*/
static const char builtin_code[] = {
    0x70, 0x72, 0x6f, 0x63, 0x20, 0x23, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6f, 0x75, 0x74, 0x28, 0x62, 0x75,
    0x66, 0x3a, 0x20, 0x5e, 0x63, 0x68, 0x61, 0x72, 0x2c, 0x20, 0x73, 0x69, 0x7a, 0x65, 0x3a, 0x20, 0x75,
    0x73, 0x69, 0x7a, 0x65, 0x29, 0x20, 0x3d, 0x3e, 0x20, 0x73, 0x73, 0x69, 0x7a, 0x65, 0x3b, 0x0a, 0x70,
    0x72, 0x6f, 0x63, 0x20, 0x23, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x28, 0x62, 0x75, 0x66, 0x3a, 0x20,
    0x5e, 0x63, 0x68, 0x61, 0x72, 0x2c, 0x20, 0x73, 0x69, 0x7a, 0x65, 0x3a, 0x20, 0x75, 0x73, 0x69, 0x7a,
    0x65, 0x29, 0x20, 0x3d, 0x3e, 0x20, 0x73, 0x73, 0x69, 0x7a, 0x65, 0x3b, 0x0a, 0x00};

static bool init_intrinsics()
{
    static const StringView names[INTRINSIC_COUNT] = {
        [INTRINSIC_READIN] = string_view_lit("#readin"),
        [INTRINSIC_WRITEOUT] = string_view_lit("#writeout"),
    };

    for (int i = 0; i < INTRINSIC_COUNT; i += 1) {
        const StringView* str_view = names + i;
        Identifier* ident = intern_ident(str_view->str, str_view->len);

        if (!ident) {
            return false;
        }

        ident->kind = IDENTIFIER_INTRINSIC;
        ident->intrinsic = (Intrinsic)i;

        intrinsic_names[i] = ident->str;
    }

    return true;
}

static bool init_keywords()
{
    static const StringView names[KW_COUNT] = {
        [KW_VAR] = string_view_lit("var"),
        [KW_CONST] = string_view_lit("const"),
        [KW_ENUM] = string_view_lit("enum"),
        [KW_UNION] = string_view_lit("union"),
        [KW_STRUCT] = string_view_lit("struct"),
        [KW_PROC] = string_view_lit("proc"),
        [KW_TYPEDEF] = string_view_lit("typedef"),
        [KW_SIZEOF] = string_view_lit("#sizeof"),
        [KW_TYPEOF] = string_view_lit("#typeof"),
        [KW_STATIC_ASSERT] = string_view_lit("#static_assert"),
        [KW_EXPORT] = string_view_lit("export"),
        [KW_IMPORT] = string_view_lit("import"),
        [KW_FROM] = string_view_lit("from"),
        [KW_AS] = string_view_lit("as"),
        [KW_INCLUDE] = string_view_lit("#include"),
        [KW_LABEL] = string_view_lit("label"),
        [KW_GOTO] = string_view_lit("goto"),
        [KW_BREAK] = string_view_lit("break"),
        [KW_CONTINUE] = string_view_lit("continue"),
        [KW_RETURN] = string_view_lit("return"),
        [KW_IF] = string_view_lit("if"),
        [KW_ELSE] = string_view_lit("else"),
        [KW_WHILE] = string_view_lit("while"),
        [KW_DO] = string_view_lit("do"),
        [KW_FOR] = string_view_lit("for"),
        [KW_SWITCH] = string_view_lit("switch"),
        [KW_CASE] = string_view_lit("case"),
        [KW_UNDERSCORE] = string_view_lit("_"),
    };

    for (int i = 0; i < KW_COUNT; i += 1) {
        const StringView* str_view = names + i;
        Identifier* ident = intern_ident(str_view->str, str_view->len);

        if (!ident) {
            return false;
        }

        ident->kind = IDENTIFIER_KEYWORD;
        ident->kw = (Keyword)i;

        keyword_names[i] = ident->str;
    }

    return true;
}

bool nibble_init(OS target_os, Arch target_arch)
{
    static const char main_name[] = "main";

    Allocator bootstrap = allocator_create(32768);
    nibble = alloc_type(&bootstrap, NibbleCtx, true);

    nibble->target_os = target_os;
    nibble->target_arch = target_arch;
    nibble->gen_mem = bootstrap;
    nibble->ast_mem = allocator_create(16384);
    nibble->tmp_mem = allocator_create(4096);
    nibble->errors = byte_stream_create(&nibble->gen_mem);
    nibble->str_lit_map = hmap(6, NULL);
    nibble->ident_map = hmap(8, NULL);
    nibble->mod_map = hmap(6, NULL);
    nibble->type_cache.ptrs = hmap(6, NULL);
    nibble->type_cache.arrays = hmap(6, NULL);
    nibble->type_cache.procs = hmap(6, NULL);

    if (!init_keywords())
        return false;

    if (!init_intrinsics())
        return false;

    if (!init_annotations())
        return false;

    main_proc_ident = intern_ident(main_name, sizeof(main_name) - 1);

    assert(nibble->ident_map.len == (KW_COUNT + ANNOTATION_COUNT + INTRINSIC_COUNT + 1));

    bucket_list_init(&nibble->vars, &nibble->ast_mem, 32);
    bucket_list_init(&nibble->procs, &nibble->ast_mem, 32);

    init_builtin_types(target_os, target_arch, &nibble->ast_mem, &nibble->type_cache);

    if (!init_code_gen(target_os, target_arch))
        return false;

    return true;
}

static Module* get_module(NibbleCtx* ctx, StrLit* cpath_lit)
{
    uint64_t* pval = hmap_get(&ctx->mod_map, PTR_UINT(cpath_lit));
    Module* mod = pval ? (void*)*pval : NULL;

    return mod;
}

static bool add_builtin_type_symbol(NibbleCtx* ctx, const char* name, Type* type)
{
    Identifier* sym_name = intern_ident(name, cstr_len(name));
    Module* builtin_mod = &ctx->builtin_mod;

    if (lookup_scope_symbol(&builtin_mod->scope, sym_name)) {
        ProgRange range = {0};
        report_error(builtin_mod->cpath_lit->str, range, "[INTERNAL ERROR] Duplicate definition of builtin `%s`",
                     sym_name);
        return false;
    }

    Symbol* sym = new_symbol_builtin_type(&ctx->ast_mem, sym_name, type, builtin_mod);

    add_scope_symbol(&builtin_mod->scope, sym_name, sym, true);

    return true;
}

static void init_builtin_syms(NibbleCtx* ctx)
{
    size_t num_types = ARRAY_LEN(builtin_types);

    for (size_t i = 0; i < num_types; i += 1) {
        BuiltinType* builtin = builtin_types + i;

        add_builtin_type_symbol(ctx, builtin->name, builtin->type);
    }
}

#define NIBBLE_INCLUDE_LIMIT 50

typedef struct CachedInclude {
    struct CachedInclude* next;
    Path* includer_ospath;
    size_t len;
    char str[];
} CachedInclude;

static bool parse_code_recursive(NibbleCtx* ctx, Module* mod, const char* cpath_str, size_t cpath_len, const char* code,
                                 HMap* seen_includes, int include_depth)
{
    Parser parser = {0};

    parser_init(&parser, &ctx->ast_mem, &ctx->tmp_mem, code, 0, &ctx->errors);
    next_token(&parser);

    while (!is_token_kind(&parser, TKN_EOF)) {
        Stmt* stmt = parse_global_stmt(&parser);

        if (!stmt || nibble->errors.count)
            return false;

        if (stmt->kind == CST_StmtInclude) {
            StmtInclude* stmt_include = (StmtInclude*)stmt;

            Path file_ospath;
            cpath_str_to_ospath(&ctx->tmp_mem, &file_ospath, cpath_str, cpath_len, &ctx->base_ospath);

            if (include_depth > NIBBLE_INCLUDE_LIMIT) {
                report_error(file_ospath.str, stmt->range,
                             "Include limit exceeded. File include chain exceeded the current threshold of `%d`.",
                             NIBBLE_INCLUDE_LIMIT);
                return false;
            }

            Path include_ospath;
            NibblePathErr ret = get_import_ospath(&include_ospath, stmt_include->file_pathname, &ctx->base_ospath,
                                                  &file_ospath, &ctx->tmp_mem);

            // Check if included file's path exists somewhere.
            if (ret == NIB_PATH_INV_PATH) {
                report_error(file_ospath.str, stmt->range, "Invalid include path \"%s\"",
                             stmt_include->file_pathname->str);
                return false;
            }

            // Check for .nib extension.
            if (ret == NIB_PATH_INV_EXT) {
                report_error(file_ospath.str, stmt->range, "Included file \"%s\" does not end in `.%s`",
                             stmt_include->file_pathname->str, nib_ext);
                return false;
            }

            assert(ret == NIB_PATH_OK);
            Path include_cpath;
            ret = ospath_to_cpath(&include_cpath, &include_ospath, &ctx->base_ospath, &ctx->tmp_mem);

            // Check that include path is inside the project's root directory.
            if (ret == NIB_PATH_OUTSIDE_ROOT) {
                report_error(file_ospath.str, stmt->range,
                             "Relative include path \"%s\" is outside of project root dir \"%s\"",
                             stmt_include->file_pathname->str, ctx->base_ospath.str);
                return false;
            }

            assert(ret == NIB_PATH_OK);

            // Check that the include file is not the same as the current file.
            if (cstr_ncmp(cpath_str, include_cpath.str, include_cpath.len) == 0) {
                report_error(file_ospath.str, stmt->range,
                             "Cyclic file inclusion detected at file `%s`. Cannot include self.", file_ospath.str);
                return false;
            }

            // Check if the file we're trying to include is in the seen_includes table.
            // If yes, fail. Otherwise, add.
            u64 key = hash_bytes(include_cpath.str, include_cpath.len);
            CachedInclude* cached_include = NULL;
            bool seen = false;

            // Look to see if this include file has already been seen.
            {
                u64* pval = hmap_get(seen_includes, key);

                if (pval) {
                    CachedInclude* cached = (void*)*pval;

                    for (CachedInclude* it = cached; it; it = it->next) {
                        if ((it->len == include_cpath.len) &&
                            (cstr_ncmp(it->str, include_cpath.str, include_cpath.len) == 0)) {
                            seen = true;
                            cached_include = it;
                            break;
                        }
                    }
                }
            }

            if (seen) {
                report_error(file_ospath.str, stmt->range,
                             "Cyclic file inclusion detected.\nFile `%s` was first included by `%s`",
                             include_ospath.str, cached_include->includer_ospath->str);
                return false;
            }

            // Add to seen_includes
            {
                CachedInclude* new_cached_include = mem_allocate(
                    &ctx->tmp_mem, offsetof(CachedInclude, str) + include_cpath.len + 1, DEFAULT_ALIGN, true);

                if (!new_cached_include) {
                    NIBBLE_FATAL_EXIT("Out of memory: %s:%d", __FILE__, __LINE__);
                    return false;
                }

                new_cached_include->next = cached_include;
                new_cached_include->len = include_cpath.len;
                new_cached_include->includer_ospath = &file_ospath;

                memcpy(new_cached_include->str, include_cpath.str, include_cpath.len);
                new_cached_include->str[include_cpath.len] = '\0';

                hmap_put(seen_includes, key, (uintptr_t)new_cached_include);
            }

            const char* included_code = slurp_file(&ctx->gen_mem, include_ospath.str);

            if (!parse_code_recursive(ctx, mod, include_cpath.str, include_cpath.len, included_code, seen_includes,
                                      include_depth + 1)) {
                return false;
            }
        }
        else if (stmt->kind == CST_StmtImport) {
            StmtImport* stmt_import = (StmtImport*)stmt;

            // NOTE: A namespaced import only really imports one new symbol into a module.
            // NOTE: TODO: This is inaccurate for greedy imports (import all symbols raw)
            size_t num_imports = stmt_import->mod_namespace ? 1 : stmt_import->num_imports;

            mod->num_imports += num_imports;
            list_add_last(&mod->import_stmts, &stmt->lnode);
        }
        else if (stmt->kind == CST_StmtExport) {
            StmtExport* stmt_export = (StmtExport*)stmt;

            mod->num_exports += stmt_export->num_exports;
            list_add_last(&mod->export_stmts, &stmt->lnode);
        }
        else {
            if (stmt->kind == CST_StmtDecl) {
                StmtDecl* stmt_decl = (StmtDecl*)stmt;

                mod->num_decls += 1;
                if (stmt_decl->decl->flags & DECL_IS_EXPORTED)
                    mod->num_exports += 1;
            }

            list_add_last(&mod->stmts, &stmt->lnode);
        }

#ifdef NIBBLE_PRINT_DECLS
        ftprint_out("%s\n", ftprint_stmt(&ctx->gen_mem, stmt));
#endif
    }

#ifdef NIBBLE_PRINT_DECLS
    ftprint_out("\n");
#endif

    return true;
}

static bool parse_code(NibbleCtx* ctx, Module* mod, const char* code)
{
    AllocatorState tmp_state = allocator_get_state(&ctx->tmp_mem);
    HMap seen_includes = hmap(3, &ctx->tmp_mem);

    bool ret = parse_code_recursive(ctx, mod, mod->cpath_lit->str, mod->cpath_lit->len, code, &seen_includes, 0);
    allocator_restore_state(tmp_state);

    return ret;
}

static bool parse_module(NibbleCtx* ctx, Module* mod);

static Module* parse_import_module(NibbleCtx* ctx, const char* path, size_t len)
{
    StrLit* cpath_lit = intern_str_lit(path, len);
    Module* mod = get_module(ctx, cpath_lit);

    if (!mod) {
        mod = alloc_type(&ctx->ast_mem, Module, true);

        module_init(mod, cpath_lit);
        hmap_put(&ctx->mod_map, PTR_UINT(mod->cpath_lit), PTR_UINT(mod));

        if (!parse_module(ctx, mod)) {
            return NULL;
        }
    }

    return mod;
}

bool import_builtin_syms(NibbleCtx* ctx, Module* mod)
{
    Module* src_mod = &ctx->builtin_mod;
    List* head = &src_mod->scope.sym_list;
    List* it = head->next;

    while (it != head) {
        Symbol* sym = list_entry(it, Symbol, lnode);

        if (!module_add_global_sym(mod, sym->name, sym)) {
            return false;
        }

        it = it->next;
    }

    return true;
}

static bool parse_module(NibbleCtx* ctx, Module* mod)
{
    ftprint_out("[INFO]: Parsing module %s ...\n", mod->cpath_lit->str);

    const char* code = NULL;

    AllocatorState mem_state = allocator_get_state(&ctx->tmp_mem);

    // Parse the code text
    Path mod_ospath;
    cpath_str_to_ospath(&ctx->tmp_mem, &mod_ospath, mod->cpath_lit->str, mod->cpath_lit->len, &ctx->base_ospath);

    code = slurp_file(&ctx->gen_mem, mod_ospath.str);

    if (!parse_code(ctx, mod, code)) {
        return false;
    }

    module_init_tables(mod, &ctx->ast_mem, ctx->num_builtins);

    // Import all builtin symbols.
    if (!import_builtin_syms(ctx, mod)) {
        return false;
    }

    // Install unresolved decls into the module's symbol table, and install exported decls into
    // the module's export table.
    if (!install_module_decls(&ctx->ast_mem, mod)) {
        return false;
    }

    // Process imports.
    {
        List* head = &mod->import_stmts;
        List* it = head->next;

        while (it != head) {
            Stmt* stmt = list_entry(it, Stmt, lnode);

            assert(stmt->kind == CST_StmtImport);
            StmtImport* simport = (StmtImport*)stmt;

            // TODO: IMPORTANT: Cache canonical import module paths to avoid expensive path construction
            // and validation!!!
            //
            // Key: Current canonical directory + raw import path
            // Val: A valid/existing canonical path for the imported module

            //
            // Create a canonical module path from import path.
            //
            // 1. Create an absolute OS path to the imported module and check if it exists.
            // 2. If it exists, subtract base_ospath to generate the canonical module path.

            Path import_mod_ospath;
            NibblePathErr ret_err = get_import_ospath(&import_mod_ospath, simport->mod_pathname, &ctx->base_ospath,
                                                      &mod_ospath, &ctx->tmp_mem);
            // Check if imported module's path exists somewhere.
            if (ret_err == NIB_PATH_INV_PATH) {
                report_error(mod_ospath.str, stmt->range, "Invalid module import path \"%s\"",
                             simport->mod_pathname->str);
                return false;
            }

            // Check for .nib extension.
            if (ret_err == NIB_PATH_INV_EXT) {
                report_error(mod_ospath.str, stmt->range, "Imported module file \"%s\" does not end in `.%s`",
                             simport->mod_pathname->str, nib_ext);
                return false;
            }

            assert(ret_err == NIB_PATH_OK);

            // Try to create a canonical module path (where `/` corresponds to main's home directory).
            Path import_cpath;
            ret_err = ospath_to_cpath(&import_cpath, &import_mod_ospath, &ctx->base_ospath, &ctx->tmp_mem);

            // Check that import module path is inside the project's root directory.
            if (ret_err == NIB_PATH_OUTSIDE_ROOT) {
                report_error(mod_ospath.str, stmt->range,
                             "Relative module import path \"%s\" is outside of project root dir \"%s\"",
                             simport->mod_pathname->str, ctx->base_ospath.str);
                return false;
            }

            assert(ret_err == NIB_PATH_OK);

            //
            // Parse import module
            //

            Module* import_mod = parse_import_module(ctx, import_cpath.str, import_cpath.len);

            if (!import_mod) {
                return false;
            }

            bool have_import_syms = !list_empty(&simport->import_syms);
            bool have_import_ns = simport->mod_namespace != NULL;

            if (have_import_ns) {
                Symbol* import_mod_sym = new_symbol_mod(&ctx->ast_mem, simport, import_mod, mod);

                if (!module_add_global_sym(mod, import_mod_sym->name, import_mod_sym)) {
                    return false;
                }
            }
            else if (have_import_syms) {
                if (!import_mod_syms(mod, import_mod, simport))
                    return false;
            }
            else {
                if (!import_all_mod_syms(mod, import_mod))
                    return false;
            }

            it = it->next;
        }
    }

    // Process exports
    {
        List* head = &mod->export_stmts;
        List* it = head->next;

        while (it != head) {
            Stmt* stmt = list_entry(it, Stmt, lnode);

            assert(stmt->kind == CST_StmtExport);
            StmtExport* sexport = (StmtExport*)stmt;

            List* h = &sexport->export_syms;

            for (List* i = h->next; i != h; i = i->next) {
                PortSymbol* esym = list_entry(i, PortSymbol, lnode);

                // Lookup the symbol we're trying to export.
                Symbol* sym = lookup_scope_symbol(&mod->scope, esym->name);

                if (!sym) {
                    report_error(mod_ospath.str, esym->range, "Unknown export symbol `%s`", esym->name->str);
                    return false;
                }

                // Prevent users from exporting builtin symbols.
                if (sym->home == &ctx->builtin_mod) {
                    report_error(mod_ospath.str, esym->range, "Cannot export builtin symbol `%s`", esym->name->str);
                    return false;
                }

                // Add symbol to the module's export table
                if (!module_add_export_sym(mod, esym->rename ? esym->rename : esym->name, sym)) {
                    report_error(mod_ospath.str, esym->range, "Conflicting export symbol name `%s`", esym->name->str);
                    return false;
                }
            }

            it = it->next;
        }
    }

    allocator_restore_state(mem_state);
    return true;
}

void nibble_compile(const char* main_file, const char* output_file)
{
    //////////////////////////////////////////
    //      Check main file validity
    //////////////////////////////////////////
    static const char builtin_mod_name[] = "/_nibble_builtin";

    AllocatorState mem_state = allocator_get_state(&nibble->tmp_mem);

    Path main_path;
    path_init(&main_path, &nibble->tmp_mem);
    path_set(&main_path, main_file, cstr_len(main_file));

    if (!path_abs(&main_path)) {
        ftprint_err("[ERROR]: Cannot find file `%s`\n", main_file);
        return;
    }

    FileKind file_kind = path_kind(&main_path);

    if ((file_kind != FILE_REG) || cstr_cmp(path_ext(&main_path), nib_ext) != 0) {
        ftprint_err("[ERROR]: Program main file must end in `.nib`\n");
        return;
    }

    /////////////////////////////////////////////////////////
    //      Get main file's module path (e.g., /main.nib)
    //      and extract the base OS path.
    /////////////////////////////////////////////////////////
    const char* filename_ptr = path_filename(&main_path);
    assert(filename_ptr != main_path.str);
    const char* base_path_end_ptr = filename_ptr - 1;

    Path* base_ospath = &nibble->base_ospath;
    path_init(base_ospath, &nibble->gen_mem);
    path_set(base_ospath, main_path.str, (base_path_end_ptr - main_path.str));

    ftprint_out("[INFO]: Base project OS path: %s\n", base_ospath->str);

    size_t cpath_cap = ((main_path.str + main_path.len) - base_path_end_ptr) + 1;
    char* entry_cpath_buf = array_create(&nibble->tmp_mem, char, cpath_cap);
    ftprint_char_array(&entry_cpath_buf, true, "%c%s", NIBBLE_PATH_SEP, filename_ptr);

    // Main module
    Module* main_mod = alloc_type(&nibble->ast_mem, Module, true);

    module_init(main_mod, intern_str_lit(entry_cpath_buf, cstr_len(entry_cpath_buf)));
    hmap_put(&nibble->mod_map, PTR_UINT(main_mod->cpath_lit), PTR_UINT(main_mod));

    /// Builtin module
    Module* builtin_mod = &nibble->builtin_mod;

    module_init(builtin_mod, intern_str_lit(builtin_mod_name, sizeof(builtin_mod_name) - 1));
    hmap_put(&nibble->mod_map, PTR_UINT(builtin_mod->cpath_lit), PTR_UINT(builtin_mod)); // TODO: Necessary?

    //////////////////////////////////////////
    //                Parse
    //////////////////////////////////////////
    ftprint_out("[INFO]: Parsing builtin module\n");

    const size_t num_builtin_types = ARRAY_LEN(builtin_types);
    bool parse_ok = parse_code(nibble, builtin_mod, builtin_code);

    if (!parse_ok) {
        ftprint_err("[ERROR]: Failed to parse builtin code\n");
        print_errors(&nibble->errors);
        return;
    }

    nibble->num_builtins = builtin_mod->num_decls + num_builtin_types;
    builtin_mod->scope.sym_table = hmap(calc_hmap_size(nibble->num_builtins << 1), &nibble->ast_mem);

    init_builtin_syms(nibble);

    if (!install_module_decls(&nibble->ast_mem, builtin_mod)) {
        print_errors(&nibble->errors);
        return;
    }

    // Parse main module.
    if (!parse_module(nibble, main_mod)) {
        print_errors(&nibble->errors);
        return;
    }

    // Look for main to have been parsed and installed as an unresolved proc symbol.
    Symbol* main_sym = lookup_symbol(&main_mod->scope, main_proc_ident);

    if (!main_sym || (main_sym->kind != SYMBOL_PROC)) {
        ftprint_err("[ERROR]: Program entry file must define a main() procedure.\n");
        return;
    }

    //////////////////////////////////////////
    //          Resolve/Typecheck
    //////////////////////////////////////////
    ftprint_out("[INFO]: Type-checking ...\n");

    Resolver resolver = {.ctx = nibble};

    if (!resolve_module(&resolver, main_mod)) {
        print_errors(&nibble->errors);
        return;
    }

    if (!resolve_reachable_sym_defs(&resolver)) {
        print_errors(&nibble->errors);
        return;
    }

    // Ensure main has the expected type signature.
    Type* main_type = main_sym->type;
    assert(main_type->kind == TYPE_PROC);
    Type* main_ret_type = main_type->as_proc.ret;

    if (main_ret_type != builtin_types[BUILTIN_TYPE_INT].type) {
        ftprint_err("[ERROR]: Main procedure must return an `int` (`%s`) type, but found `%s`.\n",
                    type_name(builtin_types[BUILTIN_TYPE_INT].type), type_name(main_ret_type));
        return;
    }

    size_t main_num_params = main_type->as_proc.num_params;

    // Check that params are either main(argc: int) or main(argc: int, argv: ^^char)
    if (main_num_params > 0) {
        Type** param_types = main_type->as_proc.params;

        if (param_types[0] != builtin_types[BUILTIN_TYPE_INT].type) {
            ftprint_err("[ERROR]: Main procedure's first paramater must be an `int` (`%s`) type, but found `%s`.\n",
                        type_name(builtin_types[BUILTIN_TYPE_INT].type), type_name(param_types[0]));
            return;
        }

        // TODO: Allow argv : []^char
        if ((main_num_params == 2) && (param_types[1] != type_ptr_ptr_char)) {
            ftprint_err("[ERROR]: Main procedure's second paramater must be a `^^char` type, but found `%s`.\n",
                        type_name(param_types[0]));
            return;
        }

        // TODO: Allow/check for envp param
    }

    ftprint_out("[INFO]: global vars: %u\tglobal procs: %u\n", nibble->vars.num_elems, nibble->procs.num_elems);

    //////////////////////////////////////////
    //          Gen NASM output
    //////////////////////////////////////////
    ftprint_out("[INFO]: Generating IR bytecode\n");
    IR_gen_bytecode(&nibble->ast_mem, &nibble->tmp_mem, &nibble->procs, &nibble->type_cache);

    //////////////////////////////////////////
    //          Gen NASM output
    //////////////////////////////////////////
    ftprint_out("[INFO]: Generating NASM assembly output: %s ...\n", output_file);
    gen_module(&nibble->gen_mem, &nibble->tmp_mem, &nibble->vars, &nibble->procs, &nibble->str_lit_map, output_file);

    allocator_restore_state(mem_state);
}

void nibble_cleanup(void)
{
#ifndef NDEBUG
    print_allocator_stats(&nibble->gen_mem, "GEN mem stats");
    print_allocator_stats(&nibble->ast_mem, "AST mem stats");
    print_allocator_stats(&nibble->tmp_mem, "TMP mem stats");
    ftprint_out("Ident map: len = %lu, cap = %lu, total_size (malloc) = %lu\n", nibble->ident_map.len,
                nibble->ident_map.cap, nibble->ident_map.cap * sizeof(HMapEntry));
    ftprint_out("StrLit map: len = %lu, cap = %lu, total_size (malloc) = %lu\n", nibble->str_lit_map.len,
                nibble->str_lit_map.cap, nibble->str_lit_map.cap * sizeof(HMapEntry));
    ftprint_out("Module map: len = %lu, cap = %lu, total_size (malloc) = %lu\n", nibble->mod_map.len,
                nibble->mod_map.cap, nibble->mod_map.cap * sizeof(HMapEntry));
    ftprint_out("type_ptr cache: len = %lu, cap = %lu, total_size (malloc) = %lu\n", nibble->type_cache.ptrs.len,
                nibble->type_cache.ptrs.cap, nibble->type_cache.ptrs.cap * sizeof(HMapEntry));
    ftprint_out("type_array cache: len = %lu, cap = %lu, total_size (malloc) = %lu\n", nibble->type_cache.arrays.len,
                nibble->type_cache.arrays.cap, nibble->type_cache.arrays.cap * sizeof(HMapEntry));
    ftprint_out("type_proc cache: len = %lu, cap = %lu, total_size (malloc) = %lu\n", nibble->type_cache.procs.len,
                nibble->type_cache.procs.cap, nibble->type_cache.procs.cap * sizeof(HMapEntry));
#endif

    hmap_destroy(&nibble->str_lit_map);
    hmap_destroy(&nibble->ident_map);
    hmap_destroy(&nibble->mod_map);
    hmap_destroy(&nibble->type_cache.ptrs);
    hmap_destroy(&nibble->type_cache.procs);
    hmap_destroy(&nibble->type_cache.arrays);
    allocator_destroy(&nibble->tmp_mem);
    allocator_destroy(&nibble->ast_mem);

    Allocator bootstrap = nibble->gen_mem;
    allocator_destroy(&bootstrap);
}

StrLit* intern_str_lit(const char* str, size_t len)
{
    Allocator* allocator = &nibble->gen_mem;
    HMap* strmap = &nibble->str_lit_map;

    uint64_t key = hash_bytes(str, len);
    uint64_t* pval = hmap_get(strmap, key);
    StrLit* intern = pval ? (void*)*pval : NULL;

    // Collisions will only occur if identical hash values are produced. Collisions due to
    // contention for hash map slots will not occur (open addressing).
    //
    // Walk the linked list in case of collision.
    for (StrLit* it = intern; it; it = it->next) {
        if ((it->len == len) && (cstr_ncmp(it->str, str, len) == 0))
            return it;
    }

    // If we got here, need to add this string to the intern table.
    StrLit* new_intern = mem_allocate(allocator, offsetof(StrLit, str) + len + 1, DEFAULT_ALIGN, true);

    if (!new_intern) {
        // TODO: Handle in a better way.
        ftprint_err("[INTERNAL ERROR]: Out of memory.\n%s:%d\n", __FILE__, __LINE__);
        exit(1);
        return NULL;
    }

    new_intern->next = intern; // Record collision. If a collision did _NOT_ occur, this will be null.
    new_intern->id = strmap->len;
    new_intern->len = len;

    memcpy(new_intern->str, str, len);
    new_intern->str[len] = '\0';

    hmap_put(strmap, key, (uintptr_t)new_intern);

    return new_intern;
}

Identifier* intern_ident(const char* str, size_t len)
{
    Allocator* allocator = &nibble->gen_mem;
    HMap* strmap = &nibble->ident_map;
    uint64_t key = hash_bytes(str, len);
    uint64_t* pval = hmap_get(strmap, key);
    Identifier* intern = pval ? (void*)*pval : NULL;

    // Collisions will only occur if identical hash values are produced. Collisions due to
    // contention for hash map slots will not occur (open addressing).
    //
    // Walk the linked list in case of collision.
    for (Identifier* it = intern; it; it = it->next) {
        if ((it->len == len) && (cstr_ncmp(it->str, str, len) == 0)) {
            return it;
        }
    }

    // If we got here, need to add this string to the intern table.
    Identifier* new_intern = mem_allocate(allocator, offsetof(Identifier, str) + len + 1, DEFAULT_ALIGN, true);

    if (!new_intern) {
        // TODO: Handle in a better way.
        ftprint_err("[INTERNAL ERROR]: Out of memory.\n%s:%d\n", __FILE__, __LINE__);
        exit(1);
        return NULL;
    }

    new_intern->next = intern; // Record collision. If a collision did _NOT_ occur, this will be null.
    new_intern->len = len;

    memcpy(new_intern->str, str, len);
    new_intern->str[len] = '\0';

    hmap_put(strmap, key, (uintptr_t)new_intern);

    return new_intern;
}

void nibble_fatal_exit(const char* format, ...)
{
    va_list vargs;

    ftprint_err("[FATAL ERROR]: ");

    va_start(vargs, format);
    ftprintv_err(format, vargs);
    va_end(vargs);

    ftprint_err("\n");

    exit(1);
}
